theme: jekyll-theme-minimal
title: 💻💼💖
description: Hello, I am Pak-Yen, a second year undergraduate student. Explore my CV!

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"

social-network-links:
  email: "pakyenloke@gmail.com"
  rss: true  # remove this line if you don't want to show an RSS link at the bottom
  linkedin: lokepak-yen
  github: pyloke-web


share-links-active:
  linkedin: true
  
url-pretty: "https://pyloke-web.github.io/digital-cv/"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
